production:
  type: ocp
  bundle:
    registry: quay.io
    organization: community-operators-pipeline
  index:
    registry: quay.io
    organization: community-operators-pipeline
    name: catalog
    tags:
      - v4.6
      - v4.7
      - v4.8
    latest: v4.6
    signature: 1
  mirror:
    enabled: 1
    multiarch: 
      base: registry.redhat.io/openshift4/ose-operator-registry:v4.5
      postfix: s
    registry: quay.io
    organization: community-operators-pipeline
    name: catalog_prod
    username:
      in: mavala
      out: framework_automation

pipeline:
  base: https://github.com
  repo: redhat-openshift-ecosystem/community-operators-pipeline
  branch: main
  ci_scripts_dir: https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/latest/ci/scripts
  image: quay.io/operator_testing/operator-test-playbooks:latest
  automerge:
    enabled: 1
  reviewers:
    enabled: 0

operatorhubio:
  enabled: 0
  registry: quay.io
  organization: operator-framework
  name: upstream-community-operators
  tag: latest

#base:
#  organisation: operator-framework
#  project: operator-test-playbooks
#  tag: master
tools:
  kind_version: v0.9.0
  kind_kube_version: v1.21.1
  operator_sdk_version: v1.8.0
